# Generated by Django 5.1.1 on 2024-10-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenetrationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_primary_contact', models.CharField(max_length=100)),
                ('team_primary_phone', models.CharField(max_length=20)),
                ('team_primary_pager', models.CharField(blank=True, max_length=20, null=True)),
                ('team_secondary_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('team_secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('team_secondary_pager', models.CharField(blank=True, max_length=20, null=True)),
                ('target_primary_contact', models.CharField(max_length=100)),
                ('target_primary_phone', models.CharField(max_length=20)),
                ('target_primary_pager', models.CharField(blank=True, max_length=20, null=True)),
                ('target_secondary_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('target_secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('target_secondary_pager', models.CharField(blank=True, max_length=20, null=True)),
                ('debrief_frequency', models.CharField(max_length=100)),
                ('debrief_location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('test_times', models.CharField(max_length=100)),
                ('announced_test', models.CharField(max_length=10)),
                ('shun_ip', models.CharField(max_length=10)),
                ('automatic_shun', models.TextField()),
                ('shun_steps', models.TextField()),
                ('conclude_test', models.CharField(max_length=10)),
                ('continue_test', models.TextField(blank=True, null=True)),
                ('attack_ips', models.TextField()),
                ('black_box', models.CharField(max_length=10)),
                ('viewing_policy', models.TextField()),
                ('observing_team', models.CharField(max_length=10)),
                ('target_signature', models.CharField(max_length=100)),
                ('target_date', models.DateField()),
                ('pen_test_leader', models.CharField(max_length=100)),
                ('leader_date', models.DateField()),
                ('tester_signatures', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
