# Generated by Django 5.1.1 on 2024-10-17 00:12

from django.db import migrations


def insert_initial_data(apps, schema_editor):
    Tool = apps.get_model("passive_recon", "Tool")
    Tool.objects.create(
        slug="whois",
        name="whois",
        description="WHOIS queries online servers for information such as domain contact details and IP address assignments. It can intelligently select the appropriate WHOIS server for most queries.",
    )

    Tool.objects.create(
        slug="nslookup",
        name="nslookup",
        description="Nslookup is the name of a program that lets users enter a hostname and find the corresponding IP address or domain name system (DNS) record. Users can also enter a command in nslookup to do a reverse DNS lookup and find the hostname for a specified IP address.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("passive_recon", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_initial_data)]
