# Generated by Django 5.1.1 on 2024-11-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0002_alter_profile_job_role_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_role',
            field=models.CharField(choices=[('student', 'Student'), ('developer', 'Developer'), ('sysadmin', 'System Administrator'), ('security', 'Security Specialist'), ('manager', 'IT Manager'), ('consultant', 'Consultant'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
