# Generated by Django 5.1.1 on 2024-11-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0005_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('developer', 'Developer'), ('sysadmin', 'System Administrator'), ('security', 'Security Specialist'), ('manager', 'IT Manager'), ('consultant', 'Consultant'), ('other', 'Other')], default='other', max_length=100, null=True),
        ),
    ]
