# Generated by Django 5.1.1 on 2024-10-17 00:25

from django.db import migrations


def insert_initial_data(apps, schema_editor):
    ActiveReconTool = apps.get_model("active_recon", "ActiveReconTool")
    ActiveReconTool.objects.create(
        slug="nmap",
        name="nmap",
        description="Nmap ('Network Mapper') is a free and open source utility for network discovery and security auditing. Many systems and network administrators also find it useful for tasks such as network inventory, managing service upgrade schedules, and monitoring host or service uptime. Nmap uses raw IP packets in novel ways to determine what hosts are available on the network, what services (application name and version) those hosts are offering, what operating systems (and OS versions) they are running, what type of packet filters/firewalls are in use, and dozens of other characteristics. It was designed to rapidly scan large networks, but works fine against single hosts. Nmap runs on all major computer operating systems, and official binary packages are available for Linux, Windows, and Mac OS X.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("active_recon", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_initial_data)]
