# Generated by Django 5.1.1 on 2024-10-17 00:32

from django.db import migrations


def insert_initial_data(apps, schema_editor):
    EnumerationTool = apps.get_model("enumeration", "EnumerationTool")
    EnumerationTool.objects.create(
        slug="subdomain",
        name="Subdomain",
        description="A subdomain is a domain name that is part of a larger domain. It is a subsidiary domain name, often used to organize content or to identify a specific department or section within a larger website. For example, 'blog.example.com' is a subdomain of 'example.com'. Subdomains can be useful for creating a separate identity or for separating different types of content within a website. They can also be used for weights and measures, or for other purposes.",
    )

    EnumerationTool.objects.create(
        slug="email-finder",
        name="Email-Finder",
        description="The Domain Search requires a domain name and returns a set of data about the organization, the email address found and additional information about the people owning those email addresses.",
    )

    EnumerationTool.objects.create(
        slug="snmpwalk",
        name="SNMPwalk",
        description="SNMP walk is an SNMP application that uses SNMP GETNEXT requests to collect SNMP data from network and infrastructure SNMP-enabled devices, such as switches and routers. Performing an SNMP walk can help you troubleshoot missing or inaccurate stats for networking devices and other devices polled via SNMP by confirming SNMP communication with remote devices and which object identifiers (OIDs) are responding.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("enumeration", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_initial_data)]
